/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui.admin.menu;

import com.gui.admin.login.loginAdmin;
import com.gui.mainApp.*;
import com.gui.user.login;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Pung's Computer
 */
public class adminMain extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public adminMain() {
        initComponents();
        setResizable(false);
        showDate();
        showTime();
    }
    public void showDate(){
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        txt_date.setText(sdf.format(date));
    }
    public void showTime(){
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               Date date = new Date();
               SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
               txt_time.setText(sdf.format(date));
            }
        }).start();
    }
    public void close(){
        this.setVisible(false);
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_shinOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_admin = new javax.swing.JButton();
        btn_user = new javax.swing.JButton();
        btn_history = new javax.swing.JButton();
        btn_aboutUs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        txt_time = new javax.swing.JTextField();
        panel_Main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        btn_shinOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/icons8-export-24.png"))); // NOI18N
        btn_shinOut.setBorder(null);
        btn_shinOut.setBorderPainted(false);
        btn_shinOut.setContentAreaFilled(false);
        btn_shinOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_shinOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_shinOutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/bread logo.png"))); // NOI18N

        btn_admin.setBackground(new java.awt.Color(0, 204, 204));
        btn_admin.setForeground(new java.awt.Color(0, 0, 0));
        btn_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/icons8-admin-settings-male-24.png"))); // NOI18N
        btn_admin.setText("Admin");
        btn_admin.setBorder(null);
        btn_admin.setBorderPainted(false);
        btn_admin.setContentAreaFilled(false);
        btn_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });

        btn_user.setBackground(new java.awt.Color(0, 204, 204));
        btn_user.setForeground(new java.awt.Color(0, 0, 0));
        btn_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/icons8-user-filled-30.png"))); // NOI18N
        btn_user.setText("User");
        btn_user.setToolTipText("");
        btn_user.setBorder(null);
        btn_user.setBorderPainted(false);
        btn_user.setContentAreaFilled(false);
        btn_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userActionPerformed(evt);
            }
        });

        btn_history.setBackground(new java.awt.Color(0, 204, 204));
        btn_history.setForeground(new java.awt.Color(0, 0, 0));
        btn_history.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/icons8-time-machine-26.png"))); // NOI18N
        btn_history.setText("Transaction History");
        btn_history.setBorder(null);
        btn_history.setBorderPainted(false);
        btn_history.setContentAreaFilled(false);
        btn_history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historyActionPerformed(evt);
            }
        });

        btn_aboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/icons8-user-filled-30.png"))); // NOI18N
        btn_aboutUs.setBorder(null);
        btn_aboutUs.setBorderPainted(false);
        btn_aboutUs.setContentAreaFilled(false);
        btn_aboutUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_aboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutUsActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/img/icons8-schedule-30.png"))); // NOI18N

        txt_date.setBackground(new java.awt.Color(0, 204, 204));
        txt_date.setForeground(new java.awt.Color(0, 0, 0));

        txt_time.setBackground(new java.awt.Color(0, 204, 204));
        txt_time.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(9, 9, 9)
                                .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_shinOut, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_aboutUs))
                                .addComponent(btn_admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_user, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_history, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btn_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_user, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_history, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_aboutUs)
                    .addComponent(btn_shinOut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        panel_Main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_Main.setLayout(new java.awt.CardLayout());
        getContentPane().add(panel_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 720, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
        // TODO add your handling code here:
        panel_Main.removeAll();
        panel_Main.repaint();
        panel_Main.revalidate();
        
        AdminSetting adminSetting = new AdminSetting();
        panel_Main.add(adminSetting);
    }//GEN-LAST:event_btn_adminActionPerformed

    private void btn_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userActionPerformed
        // TODO add your handling code here:
        panel_Main.removeAll();
        panel_Main.repaint();
        panel_Main.revalidate();
        
        UserSetting us = new UserSetting();
        panel_Main.add(us);
    }//GEN-LAST:event_btn_userActionPerformed

    private void btn_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historyActionPerformed
        // TODO add your handling code here:
       panel_Main.removeAll();
        panel_Main.repaint();
        panel_Main.revalidate();
        
        History history = new History();
        panel_Main.add(history);
        
    }//GEN-LAST:event_btn_historyActionPerformed

    private void btn_aboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aboutUsActionPerformed

    private void btn_shinOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_shinOutActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null,"Are You Sure Want To Sign Out?","WARNING", JOptionPane.YES_NO_OPTION);
        if(i == JOptionPane.YES_OPTION){
            loginAdmin log = new loginAdmin();
            log.setVisible(true);
            close();
        }
    }//GEN-LAST:event_btn_shinOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aboutUs;
    private javax.swing.JButton btn_admin;
    private javax.swing.JButton btn_history;
    private javax.swing.JButton btn_shinOut;
    private javax.swing.JButton btn_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_Main;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_time;
    // End of variables declaration//GEN-END:variables
}
